package com.ytdlp.android.databinding

import android.view.LayoutInflater
import android.view.View
import android.widget.EditText
import android.widget.Button
import androidx.recyclerview.widget.RecyclerView
import com.google.android.material.textfield.TextInputEditText
import com.google.android.material.button.MaterialButton

// This is a placeholder for ViewBinding generated class
// In a real project, this would be auto-generated by Android build system
class ActivityMainBinding private constructor(
    val root: View,
    val editTextUrl: TextInputEditText,
    val buttonPaste: MaterialButton,
    val buttonDownload: MaterialButton,
    val recyclerViewDownloads: RecyclerView
) {
    companion object {
        fun inflate(layoutInflater: LayoutInflater): ActivityMainBinding {
            // This is a placeholder implementation
            // In real project, ViewBinding auto-generates this
            throw UnsupportedOperationException("ViewBinding not implemented in this demo")
        }
    }
}