package com.ytdlp.android.databinding

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ProgressBar
import android.widget.TextView

// This is a placeholder for ViewBinding generated class
// In a real project, this would be auto-generated by Android build system
class ItemDownloadBinding private constructor(
    val root: View,
    val textViewTitle: TextView,
    val textViewUrl: TextView,
    val textViewStatus: TextView,
    val textViewProgress: TextView,
    val textViewFileSize: TextView,
    val textViewDownloadSpeed: TextView,
    val progressBarDownload: ProgressBar
) {
    companion object {
        fun inflate(layoutInflater: LayoutInflater, parent: ViewGroup, attachToParent: Boolean): ItemDownloadBinding {
            // This is a placeholder implementation
            // In real project, ViewBinding auto-generates this
            throw UnsupportedOperationException("ViewBinding not implemented in this demo")
        }
    }
}